### ISSUE TITLE
Add a html comment that helps identify the templates inside HTML source

### ISSUE THREAD

**Issue by mconta** [2sic/2SexyContent#77]
It would be nice to have a HTML comment inserted before and after the 2sxc html output.

In complex pages where a lot of 2sxc apps are used it helps identifying what templates are used without looking  at "Change layout & content" of all the Apps.

Here is an example, complete template path:

&lt;!-- \portals\2\2sxc\ThumbnailGallery\ThumbnailGallery.html start --&gt;

HTML APP OUTPUT HERE

&lt;!-- \portals\2\2sxc\ThumbnailGallery\ThumbnailGallery.html end --&gt;

or simplifying only AppFolder + template name:

&lt;!-- ThumbnailGallery\ThumbnailGallery.html start --&gt;

HTML APP OUTPUT HERE

&lt;!-- ThumbnailGallery\ThumbnailGallery.html end --&gt;

PS: Also DNN inserts comments with the name of the module used, example:

&lt;!-- Start_Module_3429 --&gt;

**Comment by iJungleboy** [comment]
Since it's easy to create such a comment yourself (like  or similar, there is no strong need to add this to the system. But adding it would mean adding switches to enable/disable and more, adding complexity. 
It's our strategy is to leave the HTML as untouched as possible - and since the designer can easily add this if he/she ever wants to, for the moment I'll decide to not implement this.
